version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary tools..."
      - echo "Docker runtime ready."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 831926601959.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPO_NAME="api-repository"
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S) && echo "Image tag set to $IMAGE_TAG"
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG 831926601959.dkr.ecr.ap-northeast-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 831926601959.dkr.ecr.ap-northeast-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo "Docker image pushed successfully" $REPO_NAME:$IMAGE_TAG
      - echo "Writing image details to JSON files..."
      - echo '{"imageURI": "831926601959.dkr.ecr.ap-northeast-1.amazonaws.com/'"$REPO_NAME:$IMAGE_TAG"'"}' > imageDetail.json
      - echo '[{"name": "'"$REPO_NAME"'", "imageUri": "831926601959.dkr.ecr.ap-northeast-1.amazonaws.com/'"$REPO_NAME:$IMAGE_TAG"'"}]' > imageDefinitions.json

artifacts:
  files:
    - imageDetail.json
    - imageDefinitions.json
  discard-paths: no
